/**
 * The payment-provider boundary (Payfast / Ozow).
 *
 * §10.0 bounds this hard: the ONLY thing that ever crosses it is a pharmacy
 * paying Locum Planner a monthly subscription, plus the R10 late-cancellation
 * charge riding on the same invoice. There is deliberately no payout method on
 * this interface, and adding one would change the product's legal position on
 * labour broking — not merely its architecture.
 *
 * §0.2 requires each vendor failure mode to be *inducible* on staging:
 * settlement-day outage, card decline, retry success, and timeout mid-charge.
 * The fake below can be told to produce each, which is what makes the dunning
 * state machine testable before those failures happen for real.
 */

export type ChargeOutcome =
  | { readonly kind: "succeeded"; readonly providerRef: string }
  /**
   * The bank said no. A definite answer — no money moved, and retrying later
   * may legitimately succeed (funds arrive) or never will (card expired).
   */
  | {
      readonly kind: "declined";
      readonly providerRef: string;
      readonly failureCode: string;
      /** True when retrying can never succeed without user action. */
      readonly permanent: boolean;
    }
  /**
   * No answer. This is the dangerous one, and it is deliberately distinct from
   * a decline: the charge may have succeeded at the provider while the
   * response was lost. Treating it as a failure and retrying is how a pharmacy
   * gets billed twice, which is a trust problem far worse than a late
   * collection.
   */
  | { readonly kind: "unknown"; readonly providerRef: string; readonly detail: string };

export interface PaymentProvider {
  /**
   * Attempts a charge.
   *
   * `idempotencyKey` is generated by US and persisted BEFORE the call, so a
   * charge whose response was lost can be reconciled rather than repeated.
   */
  charge(input: {
    readonly idempotencyKey: string;
    readonly subscriptionRef: string;
    readonly amountCents: number;
  }): Promise<ChargeOutcome>;

  /**
   * Looks up what actually happened to a charge we never got an answer for.
   * Without this, an `unknown` outcome can only be resolved by guessing.
   */
  lookup(idempotencyKey: string): Promise<ChargeOutcome | undefined>;
}

type ScriptedOutcome =
  | { kind: "succeed" }
  | { kind: "decline"; failureCode: string; permanent: boolean }
  | { kind: "outage"; detail: string }
  /** Succeeds at the provider but loses the response — the timeout case. */
  | { kind: "timeout_after_success" };

/**
 * Test/local provider with inducible failures (§0.2).
 *
 * `timeout_after_success` is the one worth understanding: it records the
 * charge as settled internally and then throws away the answer, exactly as a
 * network timeout after a successful settlement would. A dunning
 * implementation that retries blindly will double-charge here, and the test
 * suite will catch it.
 */
export class FakePaymentProvider implements PaymentProvider {
  private readonly settled = new Map<string, ChargeOutcome>();
  private readonly script: ScriptedOutcome[] = [];
  /** Every charge call, including ones whose response was "lost". */
  readonly attempts: string[] = [];

  /** Queue outcomes, consumed in order. Defaults to success when empty. */
  scriptOutcomes(...outcomes: ScriptedOutcome[]): void {
    this.script.push(...outcomes);
  }

  async charge(input: {
    idempotencyKey: string;
    subscriptionRef: string;
    amountCents: number;
  }): Promise<ChargeOutcome> {
    this.attempts.push(input.idempotencyKey);

    // A key we have already settled must never be charged again — this is what
    // a real provider's idempotency guarantees, and modelling it here means
    // the test can prove we rely on it rather than on luck.
    const existing = this.settled.get(input.idempotencyKey);
    if (existing) return existing;

    const next = this.script.shift() ?? { kind: "succeed" as const };
    const providerRef = `pf_${input.idempotencyKey.slice(0, 12)}`;

    switch (next.kind) {
      case "succeed": {
        const outcome: ChargeOutcome = { kind: "succeeded", providerRef };
        this.settled.set(input.idempotencyKey, outcome);
        return outcome;
      }
      case "decline":
        return {
          kind: "declined",
          providerRef,
          failureCode: next.failureCode,
          permanent: next.permanent,
        };
      case "outage":
        return { kind: "unknown", providerRef, detail: next.detail };
      case "timeout_after_success": {
        // Settled at the provider; the caller never learns that.
        this.settled.set(input.idempotencyKey, { kind: "succeeded", providerRef });
        return { kind: "unknown", providerRef, detail: "timeout after settlement" };
      }
    }
  }

  async lookup(idempotencyKey: string): Promise<ChargeOutcome | undefined> {
    return this.settled.get(idempotencyKey);
  }

  /** How many times a given key was actually charged. */
  attemptsFor(idempotencyKey: string): number {
    return this.attempts.filter((k) => k === idempotencyKey).length;
  }
}
